name: 🚀 Deploy Next.js via SSH

on:
  push:
    branches: [ master ] # можно поменять на другую ветку, если хочешь

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🧾 Checkout repository
      uses: actions/checkout@v4

    - name: 🚀 Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "🔗 Подключаемся к серверу..."
          cd /var/www/html/shop

          echo "📥 Получаем свежий код..."
          git fetch origin master
          git reset --hard origin/master

          echo "📦 Устанавливаем зависимости..."
          npm install

          echo "🔨 Собираем проект..."
          npm run build

          echo "⚡ Настраиваем PM2..."
          # Останавливаем приложение если оно запущено через npm start
          pkill -f "npm start" || true
          
          # Запускаем через PM2
          pm2 delete next-app || true
          pm2 start npm --name "next-app" -- start
          pm2 save
          pm2 startup

          echo "✅ Деплой завершен!"
          echo "📊 Статус приложения:"
          pm2 status
