name: 🔧 Test Connection

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 🧪 Test SSH and PM2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "✅ SSH Connection Successful!"
          echo "=== PM2 Status ==="
          pm2 status
          echo "=== Application Check ==="
          curl -s -o /dev/null -w "HTTP Status: %{http_code}\n" http://localhost:3000
          echo "=== Nginx Check ==="
          curl -s -o /dev/null -w "HTTPS Status: %{http_code}\n" https://colorfullshop.ru
          echo "=== Directory Contents ==="
          ls -la /var/www/html/