name: 🧪 Simple Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: 🎉 Test
      run: |
        echo "✅ Workflow is working!"
        echo "Time: $(date)"
        echo "Branch: ${{ github.ref }}"